main: me.asakura_kukii.siegemounthandler.main.Main
version: 0.0.1
api-version: 1.18
name: SiegeMountHandler
commands:
  SiegeMountHandler:
    description: Main command for SiegeMountHandler
    aliases: [smh]
permissions:
  siegemounthandler.admin:
    description: 'Gives access to all admin commands for SiegeMountHandler'
    children:
      siegemounthandler.reload: true
depend: [ProtocolLib]
author:
   Asakura_kukii